name: Website performance analysis

on:
  push:
  #   branches:
  #     - preprod

  # workflow_dispatch: ~
  # schedule:
  #   - cron: '0 10 * * 1'

jobs:
  analysis:
    uses: ./.github/workflows/standard-batch-analysis.yaml
    with:
      heart-image-name: "fabernovel/heart:standard"
    secrets:
      DAREBOOST_API_TOKEN: test1
      SLACK_API_TOKEN: test2
      SLACK_CHANNEL_ID: test3
      DOCKER_USERNAME:
      DOCKER_TOKEN:

  use-results:
    name: Check result
    needs: [analysis]
    runs-on: [self-hosted, docker]
    container:
      image: docker://node:14-buster

    steps:
      - run: echo ${{ needs.analysis.outputs.results }}
