name: Website performance analysis

# Github Events Documentation: 
on:
  # Trigger event - example 1
  push
    branches:
      - '**'
      # - 'preprod'

  # Trigger event - example 2
  workflow_dispatch: ~
  schedule:
    # Every Monday at 10:00 AM
    - cron: '0 10 * * 1'

jobs:

  # This step is recommended as good practice.
  # Comment this job if you do not want to run it.
  # Documentation : https://github.com/github/super-linter
  lint:
    runs-on: [self-hosted, docker]
    name: Lint Code

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Run a series of Heart analyses based on configuration files
  analysis:
    uses: ./.github/workflows/standard-batch-analysis.yaml
    with:
      heart-image-name: fabernovel/heart:standard
    secrets:
      DAREBOOST_API_TOKEN: ${{ secrets.DAREBOOST_API_TOKEN }}
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}